'use client';

import React, { useState, useMemo } from 'react';
import { ColumnConfig, WordClassification, WordOverrideMap } from '@/types/phonics';
import { generateCombinations } from '@/lib/lexicon/word-analyzer';
import {
  Search,
  CheckCircle2,
  HelpCircle,
  Ban,
  Sparkles,
  Undo2,
  Filter,
} from 'lucide-react';

interface WordMatrixExplorerProps {
  columns: ColumnConfig[];
  overrides: WordOverrideMap;
  onToggleOverride: (word: string, targetClassification: WordClassification) => void;
  onClearOverrides?: () => void;
}

export const WordMatrixExplorer: React.FC<WordMatrixExplorerProps> = ({
  columns,
  overrides,
  onToggleOverride,
  onClearOverrides,
}) => {
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState<'all' | WordClassification | 'overrides'>('all');

  // Compute Cartesian combinations and auto-classifications
  const combinationsResult = useMemo(() => {
    return generateCombinations(columns, overrides, 3000);
  }, [columns, overrides]);

  const { words, totalPossible, isTruncated, summary } = combinationsResult;

  const overridesCount = useMemo(() => Object.keys(overrides).length, [overrides]);

  // Filter words by search query and status pill
  const filteredWords = useMemo(() => {
    return words.filter((item) => {
      // Status filter
      if (statusFilter === 'overrides') {
        if (!item.isOverride) return false;
      } else if (statusFilter !== 'all') {
        if (item.classification !== statusFilter) return false;
      }

      // Search query
      if (searchQuery.trim()) {
        const q = searchQuery.toLowerCase().trim();
        return item.word.includes(q);
      }

      return true;
    });
  }, [words, statusFilter, searchQuery]);

  return (
    <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm overflow-hidden flex flex-col">
      {/* Top Stat Summary Banner */}
      <div className="p-6 bg-slate-50 dark:bg-slate-950/60 border-b border-slate-200 dark:border-slate-800">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h3 className="text-lg font-bold text-slate-900 dark:text-slate-100 flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
              Word Combinations Matrix & Verification
            </h3>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
              Analyzing all potential words generated by the current column cards. Never-show invalid words are automatically excluded during live board flips.
            </p>
          </div>

          {overridesCount > 0 && onClearOverrides && (
            <button
              type="button"
              onClick={onClearOverrides}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-100 bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 transition-colors shadow-sm self-start sm:self-auto"
            >
              <Undo2 className="w-3.5 h-3.5" />
              Reset Overrides ({overridesCount})
            </button>
          )}
        </div>

        {/* Aggregate Metrics Grid */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-5">
          <div className="p-3.5 rounded-xl bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 shadow-sm">
            <span className="block text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider">
              Total Combos
            </span>
            <span className="text-2xl font-black text-slate-900 dark:text-slate-100 mt-0.5 block">
              {totalPossible}
              {isTruncated && <span className="text-xs text-amber-500 font-semibold ml-1">(sample)</span>}
            </span>
          </div>

          <div className="p-3.5 rounded-xl bg-emerald-50/60 dark:bg-emerald-950/20 border border-emerald-200/80 dark:border-emerald-800/50 shadow-sm">
            <span className="block text-xs font-bold text-emerald-700 dark:text-emerald-400 uppercase tracking-wider flex items-center gap-1">
              <CheckCircle2 className="w-3.5 h-3.5" /> Real Words
            </span>
            <span className="text-2xl font-black text-emerald-700 dark:text-emerald-300 mt-0.5 block">
              {summary.realCount}
            </span>
          </div>

          <div className="p-3.5 rounded-xl bg-purple-50/60 dark:bg-purple-950/20 border border-purple-200/80 dark:border-purple-800/50 shadow-sm">
            <span className="block text-xs font-bold text-purple-700 dark:text-purple-400 uppercase tracking-wider flex items-center gap-1">
              <HelpCircle className="w-3.5 h-3.5" /> Nonsense
            </span>
            <span className="text-2xl font-black text-purple-700 dark:text-purple-300 mt-0.5 block">
              {summary.nonsenseCount}
            </span>
          </div>

          <div className="p-3.5 rounded-xl bg-rose-50/60 dark:bg-rose-950/20 border border-rose-200/80 dark:border-rose-800/50 shadow-sm">
            <span className="block text-xs font-bold text-rose-700 dark:text-rose-400 uppercase tracking-wider flex items-center gap-1">
              <Ban className="w-3.5 h-3.5" /> Excluded
            </span>
            <span className="text-2xl font-black text-rose-700 dark:text-rose-300 mt-0.5 block">
              {summary.invalidCount}
            </span>
          </div>
        </div>
      </div>

      {/* Filter and Search Bar */}
      <div className="p-4 border-b border-slate-200 dark:border-slate-800 flex flex-col sm:flex-row gap-3 bg-white dark:bg-slate-900">
        <div className="relative flex-1">
          <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
          <input
            type="text"
            placeholder="Search word combination..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-9 pr-4 py-2 text-sm bg-slate-100 dark:bg-slate-800 rounded-xl border-none focus:ring-2 focus:ring-indigo-500 text-slate-900 dark:text-slate-100 placeholder-slate-400"
          />
        </div>

        {/* Filter Pills */}
        <div className="flex items-center gap-1.5 overflow-x-auto no-scrollbar">
          <span className="text-xs text-slate-400 mr-1 flex items-center gap-1">
            <Filter className="w-3 h-3" /> Filter:
          </span>
          <button
            type="button"
            onClick={() => setStatusFilter('all')}
            className={`px-3 py-1.5 rounded-xl text-xs font-bold whitespace-nowrap transition-colors ${
              statusFilter === 'all'
                ? 'bg-slate-900 text-white dark:bg-slate-100 dark:text-slate-900 shadow-sm'
                : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-700'
            }`}
          >
            All ({summary.total})
          </button>
          <button
            type="button"
            onClick={() => setStatusFilter('real')}
            className={`px-3 py-1.5 rounded-xl text-xs font-bold whitespace-nowrap transition-colors ${
              statusFilter === 'real'
                ? 'bg-emerald-600 text-white shadow-sm'
                : 'bg-slate-100 dark:bg-slate-800 text-emerald-700 dark:text-emerald-400 hover:bg-emerald-50 dark:hover:bg-emerald-950/40'
            }`}
          >
            Real ({summary.realCount})
          </button>
          <button
            type="button"
            onClick={() => setStatusFilter('nonsense')}
            className={`px-3 py-1.5 rounded-xl text-xs font-bold whitespace-nowrap transition-colors ${
              statusFilter === 'nonsense'
                ? 'bg-purple-600 text-white shadow-sm'
                : 'bg-slate-100 dark:bg-slate-800 text-purple-700 dark:text-purple-400 hover:bg-purple-50 dark:hover:bg-purple-950/40'
            }`}
          >
            Nonsense ({summary.nonsenseCount})
          </button>
          <button
            type="button"
            onClick={() => setStatusFilter('invalid')}
            className={`px-3 py-1.5 rounded-xl text-xs font-bold whitespace-nowrap transition-colors ${
              statusFilter === 'invalid'
                ? 'bg-rose-600 text-white shadow-sm'
                : 'bg-slate-100 dark:bg-slate-800 text-rose-700 dark:text-rose-400 hover:bg-rose-50 dark:hover:bg-rose-950/40'
            }`}
          >
            Excluded ({summary.invalidCount})
          </button>
          {overridesCount > 0 && (
            <button
              type="button"
              onClick={() => setStatusFilter('overrides')}
              className={`px-3 py-1.5 rounded-xl text-xs font-bold whitespace-nowrap transition-colors ${
                statusFilter === 'overrides'
                  ? 'bg-amber-500 text-white shadow-sm'
                  : 'bg-slate-100 dark:bg-slate-800 text-amber-700 dark:text-amber-400 hover:bg-amber-50 dark:hover:bg-amber-950/40'
              }`}
            >
              Customized ({overridesCount})
            </button>
          )}
        </div>
      </div>

      {/* Words List Container */}
      <div className="flex-1 max-h-[60vh] overflow-y-auto divide-y divide-slate-100 dark:divide-slate-800">
        {filteredWords.length === 0 ? (
          <div className="text-center py-16 text-slate-400">
            No words match the selected filters.
          </div>
        ) : (
          filteredWords.map((item) => {
            return (
              <div
                key={item.word}
                className="p-4 sm:px-6 flex flex-col sm:flex-row sm:items-center justify-between gap-3 hover:bg-slate-50/70 dark:hover:bg-slate-950/40 transition-colors"
              >
                {/* Word Label & Status */}
                <div className="flex items-center gap-3">
                  <span className="font-lexend font-black text-xl text-slate-900 dark:text-slate-100 tracking-wide min-w-[5rem]">
                    {item.word}
                  </span>

                  {/* Current Status Pill */}
                  {item.classification === 'real' && (
                    <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-bold bg-emerald-100 text-emerald-800 dark:bg-emerald-950/60 dark:text-emerald-300">
                      <CheckCircle2 className="w-3.5 h-3.5" /> Real Word
                    </span>
                  )}
                  {item.classification === 'nonsense' && (
                    <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-bold bg-purple-100 text-purple-800 dark:bg-purple-950/60 dark:text-purple-300">
                      <HelpCircle className="w-3.5 h-3.5" /> Nonsense
                    </span>
                  )}
                  {item.classification === 'invalid' && (
                    <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-bold bg-rose-100 text-rose-800 dark:bg-rose-950/60 dark:text-rose-300">
                      <Ban className="w-3.5 h-3.5" /> Excluded
                    </span>
                  )}

                  {/* Reason Label if invalid */}
                  {item.reason && item.classification === 'invalid' && (
                    <span className="text-[11px] text-slate-400 italic hidden md:inline">
                      ({item.reason})
                    </span>
                  )}

                  {item.isOverride && (
                    <span className="px-2 py-0.5 rounded-md text-[10px] font-bold uppercase tracking-wider bg-amber-100 text-amber-800 dark:bg-amber-950/60 dark:text-amber-300">
                      Teacher Override
                    </span>
                  )}
                </div>

                {/* 3-Way Toggle Actions */}
                <div className="flex items-center gap-1 self-end sm:self-auto bg-slate-100 dark:bg-slate-800/80 p-1 rounded-xl border border-slate-200/60 dark:border-slate-700/60">
                  <button
                    type="button"
                    onClick={() => onToggleOverride(item.word, 'real')}
                    className={`px-2.5 py-1 rounded-lg text-xs font-bold transition-all ${
                      item.classification === 'real'
                        ? 'bg-white dark:bg-slate-900 text-emerald-700 dark:text-emerald-400 shadow-sm'
                        : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200'
                    }`}
                  >
                    Real
                  </button>
                  <button
                    type="button"
                    onClick={() => onToggleOverride(item.word, 'nonsense')}
                    className={`px-2.5 py-1 rounded-lg text-xs font-bold transition-all ${
                      item.classification === 'nonsense'
                        ? 'bg-white dark:bg-slate-900 text-purple-700 dark:text-purple-400 shadow-sm'
                        : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200'
                    }`}
                  >
                    Nonsense
                  </button>
                  <button
                    type="button"
                    onClick={() => onToggleOverride(item.word, 'invalid')}
                    className={`px-2.5 py-1 rounded-lg text-xs font-bold transition-all ${
                      item.classification === 'invalid'
                        ? 'bg-rose-600 text-white shadow-sm'
                        : 'text-rose-600 dark:text-rose-400 hover:bg-rose-50 dark:hover:bg-rose-950/40'
                    }`}
                  >
                    Hide
                  </button>
                </div>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
};
